name = "app"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_json = "~> 1.0"
lustre = "~> 4.1"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
lustre_http = ">= 0.5.2 and < 1.0.0"
plinth = ">= 0.2.0 and < 1.0.0"
gleam_community_colour = ">= 1.4.0 and < 2.0.0"
